services:
  - type: web
    name: pencatatan_warga
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate --force
      php artisan storage:link || true
      npm install
      npm run build
      php artisan config:cache
      php artisan route:cache
    startCommand: |
      php artisan serve --host 0.0.0.0 --port $PORT
